version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn dev"
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/mino:cached
      - /mino/node_modules
    tty: true

  mongo:
    image: mongo
    ports:
      - 27017:27017
