version: '3.8'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mino:cached
      - /mino/node_modules
    ports:
      - '3000:3000'
    command: yarn dev

  mongo:
    image: mongo
    ports: 27017:27017
