name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: lint-fix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: dependencies
        run: yarn install
  #       name: yarn install
  #     # - run: yarn install
  #     #   name: eslint
  #     # - run: yarn lint-fix

  # # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     # Runs a single command using the runners shell
  #     - name: Run a one-line script
  #       uses: actions/checkout@v2
  #       run: echo Hello, world!

  #     # Runs a set of commands using the runners shell
  #     - name: Run a multi-line script
  #       uses: actions/checkout@v2
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
